services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - GO_ENV=development
  mysql:
      image: mysql:latest
      container_name: mysql_container
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: my_database
        MYSQL_USER: user
        MYSQL_PASSWORD: user
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      restart: unless-stopped
      networks:
        - app_network
volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
